### ISSUE TITLE
Completed Tasks should appear for the VHT

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#41]

**Comment by ewinkler** [comment]
This is essentially the same issue as #40 in terms of trying to synch across devices.

**Comment by ewinkler** [comment]
@donrukanga1 Root of this issue is that the query used to load the Tasks into the fragment  defaults to only loading those that have status="ASSIGNED". The original idea was to use a tabbed interface which grouped by status="ASSIGNED", "COMPLETED", etc. The fragment tabs aren't currently implemented so this might be easier given current timeframe to remove the "ASSIGNED" query filter and color code based on status. Let me know what you think. 

Otherwise, the server synch doesn't currently restrict to just assigned status so they should be getting fetched.

**Comment by donrukanga1** [comment]
Oh, i also think that should do what we want.
