### ISSUE TITLE
Add voucher number field in the App

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#96]

**Comment by ewinkler** [comment]
Add the voucher id entry as the Patient.system_id. The field is in the default model but was made nullable since we had not been using it to this point. 

In the mapping forms, vht and midwife, add an Element with:
1. "type"="ENTRY" 
2. "concept"="SYSTEM_ID"
3. "required"="false"
4. "question" attribute prompt as appropriate.

Also, you may want to add:
1. One or more Elements and branching logic to skip or display the voucher id prompt.
2. Consider if any other view layer components should display the voucher id-i.e. list of patients, etc. 

@donrukanga1 I am assigning this to you to update the form.
